### PR TITLE
I added this check ...

### PR DESCRIPTION
**Pull request by MiroslavHoudek**
... when NULL was returned by that lookup_with_wildcard, and that crashed the SW, not too many lines of code later. Why it did not find the driver name, nor the \* wildcard - is probably due to my continuing misunderstanding of the merge_drivers - but this just feels more robust anyway.

### CODE REVIEW

**Comment by ethomson** [comment]
Hmm.  Can you provide more details about a reproduction case?  If there is a bug then we would want to add a test that illustrates this behavior so that we know that we do not regress.

**Comment by MiroslavHoudek** [comment]
Sure, I'm not fully on top of this whole thing yet, but now this happens when no merge drivers are defined anywhere (none are in the config, none are registered via git_merge_drivers_register) and then in a .gitattributes there is a statement like `*.xml merge=nonexistent`. The lookup function goes through all the drivers (none are there, so none fitting are found), and then it tries to falls back to \* driver (see below) . But that is not found either, and NULL is returned. Here:

```
    git_merge_driver *driver = git_merge_driver_lookup(name);

    if (driver == NULL)
        driver = git_merge_driver_lookup("*");
```

Either there needs to be the handling I wrote, or there could be a hard-coded default driver, which is always there, for example:

```
    git_merge_driver *driver = git_merge_driver_lookup(name);

    if (driver == NULL)
    {
        driver = git_merge_driver_lookup("*");

        if (driver == NULL)
            driver = &git_merge_driver__normal; // for example
    }
```

To write a test for the code as it now is to simulate the "no drivers registered yet I'm still looking up one" scenario, where the PASS is `GIT_ERR`returned by the fixed `git_merge_driver_for_source()`, but the FAIL is a segmentation fault, which is sub-optimal set up for a test.

The second option is to dismiss my fix, and go with this fix above, where merge_driver_lookup_with_wildcard() returns the default driver. The to write a unit-test test is to look for non-NULL value with (expected driver is returned) and without registered drivers (default driver is returned). But with this other fix, you mask the fact that a considerable error occurred, and you'd just silently use default driver, which is also somewhat sub-optimal.

**Comment by ethomson** [comment]
Thanks; I took care of this in https://github.com/libgit2/libgit2/pull/3564.

**Comment by MiroslavHoudek** [comment]
Awesome, thank you!

**Pull request closed without merging**
